### PR TITLE
Fixed the dynamic states not working if the user has DeskScapes enabled on his system

### LINKED ISSUE #38: Allow for blacklisting certain window classes with dynamic mode
Some programs, such as DeskScapes break the feature.

### PR DESCRIPTION
**Pull request by charlesmilette**
Partially fixes #38

### CODE REVIEW

**Comment by ethanhs** [comment]
Hi, yes this is a good idea, but there are a few problems with this: we are using unicode, so getclassnameA isn't correct, this should be done in a config file I think, and windowhandle is a confusing name, because it refers to the class name, and not the window handle. I am working on the refactor (I am going to put some time towards that wednesday, so hopefully I can integrate a feature like this there too).

**Comment by charlesmilette** [comment]
A feature like this would be helpful, and perhaps a built-in blacklist in addition with the user-made blacklist could be done so that known programs never breaks the feature even if the user has a custom blacklist.

**Comment by charlesmilette** [comment]
Also in your rebase could you add a third appearance option in the context-menu for dynamic?

**Comment by ethanhs** [comment]
Add a dynamic option in the context menu? Yes, I'm planning on doing that.

**Pull request closed without merging**
