### PR TITLE
Added description of the nColor field.

### PR DESCRIPTION
**Pull request by MrAksel**
And described an issue that arose on a single computer. This might not be very relevant, and we can probably drop it later, but it's nice documentation to have if someone else reports something similar.

### CODE REVIEW

**Comment by ethanhs** [comment]
I have reason to believe that the cause is a registry setting. If you have two computers with two different results, would you be able to look at `Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\DWM` and look for any differences in keys?

**Comment by MrAksel** [comment]
I'll do that tomorrow morning :) Need some sleep first.

**Comment by MrAksel** [comment]
Well, no difference at all between any of those keys. I'll upgrade to build 15007 some time and see if that fixes the problem.

**Comment by ethanhs** [comment]
Thanks!

**Pull request merged**
