### PR TITLE
Added support for --tint when the taskbar is blurred

### PR DESCRIPTION
**Pull request by charlesmilette**

### CODE REVIEW

**Comment by charlesmilette** [comment]
BTW, won't using printf() instead of the regular iostream fix the bug in `PrintHelp`?

**Comment by ethanhs** [comment]
Thanks for the refactoring, I was going to do this anyway, but you saved me the work :)
Could you keep the comments on what each state does? Thanks!

**Comment by charlesmilette** [comment]
Okay, gimme a minute ;)

**Comment by charlesmilette** [comment]
Done. I also changed something, because it is wrong that sending a zero nColor value makes it an opaque taskbar with the system color.

**Comment by ethanhs** [comment]
Awesome, thanks!

**Comment by charlesmilette** [comment]
Also, it'd be a pain to merge develop back into master

**Comment by ethanhs** [comment]
Yes, it may be, I will see what I can do.

**Comment by charlesmilette** [comment]
Best solution IMO would be to rebase master and remove 343ed9c671dcf4cd7682645119965eb7ceac770f and 38de61cfd572df84aa36e9d09c19143131270391, then ask @olliethepikachu to redo his PR in develop. There shouldn't be any conflicts then.

**Comment by ethanhs** [comment]
I might just make master for the Readme, and a new branch for each release.

**Comment by charlesmilette** [comment]
What I'd do is keep develop, and merge into master whenever a stable release is ready.

So all the active development occurs in develop, and master will only contain stable code. To keep an archive of the old version code, tags where made for that.

**Comment by olliethepikachu** [comment]
What @charlesmilette said.

**Comment by ethanhs** [comment]
Fair enough. I'll take the merge into master approach then.

**Comment by charlesmilette** [comment]
BTW you'll need to add `-p` as argument to Git when rebasing or else commit 343ed9c will not show and you will be able to remove it

**Comment by MrAksel** [comment]
Too bad I didn't see this earlier. What windows build are you on @charlesmilette? I'm on preview 14968, and zero nColor definitely makes the taskbar opaque with the system color scheme here. Your commit to apply --tint to the blur mode also has no effect on the color of the taskbar on my build, it's just standard blurred no matter what nColor is. It's at least clear that we shouldn't rely on the behaviour of the API here, as it may vary.

Btw, the reason I wrote that much code and comments was to clearly describe exactly those issues. I think it would be useful to preserve those comments in the code, and expand on them as we figure out how this works. The comments regarding to the ACCENT_* constants are not correct on my build, and we should therefore include as much information as we have.

**Comment by charlesmilette** [comment]
It works correctly on my machine, running the same build than you. If you want to document their behavior in description, I think the best idea is to use a separate markdown file. I'd keep it small in the code and thoroughly detailed somewhere else.

**Comment by ethanhs** [comment]
I'm in favor of keeping commrnts in the code actually. It makes it easier to read the code.

**Comment by charlesmilette** [comment]
I agree, but 10 lines of comments to describe a behavior feels like too much for me.

@MrAksel What if you try on another computer or a VM?

**Comment by MrAksel** [comment]
I will try it on my desktop shortly. Currently writing a separate doc file for this behaviour, so then we can keep your clean version of the code.

**Comment by MrAksel** [comment]
And no - I've tried using printf() to display the help messages. I think the reason is that Powershell and cmd launches the program and notes that it does not attach to the console on startup (as is usually handled before main/WinMain), but does so at a later time.

**Comment by MrAksel** [comment]
Works as you observed on my desktop (build 14931). Weird.

**Comment by olliethepikachu** [comment]
If you have Visual Studio I think debugging attaches to the executable. I'm using OutputDebugStr and through the VSCode debugger it works perfectly for printing strings to the console.

**Comment by ethanhs** [comment]
@olliethepikachu that is true, but we want the users who don't have VS to be able to use it from the command line.

**Pull request merged**
