### PR TITLE
Description of the nColor field.

### PR DESCRIPTION
**Pull request by MrAksel**
Describes the behaviour of the SetWindowCompositionAttribute function and some issues that might arise. The issue has only been observed on a single computer, so it probably isn't a problem.

### CODE REVIEW

**Comment by MrAksel** [comment]
Well this didn't go as expected. I'll tidy things up and try again.

**Comment by charlesmilette** [comment]
What I do generally is delete the fork and refork the repo.

Le jeu. 12 janv. 2017 15:43, Aksel Lunde Aase <notifications@github.com> a
écrit :

**Comment by MrAksel** [comment]
For each branch/pull request? That seems overly complicated. Might be the easiest, I'm not exactly fluent with GitHub, thanks 👍

**Comment by ethanhs** [comment]
Yeah I haven't found an easier way than what @charlesmilette said.

**Pull request closed without merging**
