### PR TITLE
Added a radio in the context menu, removed enforcing of total transparent when using clear

### PR DESCRIPTION
**Pull request by charlesmilette**
When you enforce the color to 0x00000000 when using clear, this means that any tint transmitted via CMD would be ignored.

I also added the .vscode folder in the .gitignore

### CODE REVIEW

**Comment by ethanhs** [comment]
A radio only allows 2 values, correct? I was thinking opaque might be a nice option as well... Also considering adding code to automatically grab the accent color. Thoughts?

**Comment by charlesmilette** [comment]
A radio only allows a value at once, it isn't limited to only two values.

Once we get some color picker working, I don't think opaque could be required since to reach this effect the user could only turn opacity to 100%.

The code to grab accent color could also be a single check box in the color picker that would disable and auto-fill the color mixer.

**Comment by ethanhs** [comment]
Yeah, I don't know what I was thinking. Thanks!

**Comment by charlesmilette** [comment]
I think separating the program into multiple files would help with merge conflicts and make it clearer to read. So for example someone could want to push on the message queue, you could be working on startup code and I could be working on the tray and settings features without having to worry about conflicts.

Because when I created the pull request for this one, I noticed there was a merge conflict and I had to fix it on my side.

**Comment by ethanhs** [comment]
Yes, I need to refactor the code a bit. I really meant to wrap the tray icon stuff in a header, but I didn't. I will probably do that today.

**Pull request merged**
