### PR TITLE
Updated to allow for iteration over multiple windows with class Shell_SecondaryTrayWnd (secondary taskbars)

### PR DESCRIPTION
**Pull request by olliethepikachu**
Used the [knowledge gained by @ethanhs and @PFCKrutonium](https://github.com/ethanhs/TranslucentTB/pull/1), who state that second monitors and beyond all use the same class name: Shell_SecondaryTrayWnd (the primary desktop has Shell_TrayWnd).

FindWindowEx is used with a loop to iterate over *all* HWNDs with class Shell_SecondaryTrayWnd and runs SetWindowBlur on each.

### CODE REVIEW

**Comment by ethanhs** [comment]
Thank you! I don't think I can merge this as is, and I want to test it, and put some thought into how I want configuration to go, but I will use this in some form (giving proper attribution of course). Thanks so much!

**Comment by olliethepikachu** [comment]
You're welcome! I know essentially no C++ (more of a Python/JavaScript guy), and putting together something which compiles is an achievement, especially as I didn't have the comfort of Visual Studio this time. :P

Feel free to change my (people on StackOverflow's) code all you like.

On a side note, I'm working on a project of my own (it might or might not be released open-source). Do I have permission to use a stripped-down version of your work (with proper attribution)? Thanks!

**Comment by charlesmilette** [comment]
Yeah, that config seemed extremely basic. If you add some configuration options in the future, I could write a nice configuration GUI with live preview of the settings for you @ethanhs 

If you add that, I'd also like to be able to use ACCENT_INVALID instead of BLUR_BEHIND ;)

**Comment by olliethepikachu** [comment]
It was; I know literally no C++ so this was a bit of a hacky, temporary solution. I *might* port it to Python via ctypes, though.

**Comment by ethanhs** [comment]
@charlesmilette a gui would be great! I think I'm going to keep the settings in a state struct, and then read/write to a file (settings.txt) via a line by line setup eg: `blur=0`. I've opened #3 for more discussion on settings.

@olliethepikachu I don't really see a reason to port it to Python, but let me know if you have questions, I started hacking win32 on Python before quickly moving to C#, and now C++

**Comment by olliethepikachu** [comment]
For Python compatibility I'm thinking about using it in a project of my own which is in Python and I don't want to do things the 'hacky' way with multiple executables.

Also, a GUI which writes to said settings file would be great. If you want I can use PyQt to write one, which (IMO) would be simpler but would result in two files.

**Comment by ethanhs** [comment]
@olliethepikachu for the sake of not relying on Python and keeping things light weight, I'd rather stick to C++ and win32 apis. 

Also, what is the project you are working on?

**Comment by olliethepikachu** [comment]
It's a personal project, so yeah...

And I agree that it would definitely be better if we stuck with C++, but (be warned that I know little C++) writing a GUI to do something basic like that would be easiest. If you don't feel like you need it, that'll be fine, but I was just suggesting the idea.

**Comment by charlesmilette** [comment]
We can use C# to have the tool and config GUI to be managed within the same solution.
XAML and is quite easy for making a nice looking and functional GUI

Also writing a GUI in Python would require all users to have Python installed.

**Comment by olliethepikachu** [comment]
Yea, using C++/C# would be easiest. Python and PyQt can be frozen into executables though. And I continuously forget that Visual Studio has a GUI builder as I don't have it installed. :P

**Comment by ethanhs** [comment]
I'd really like to keep this limited to C++, as it keeps everything light, a hello world in WPF is 10-100x heavier in RAM than this program currently.

**Comment by ethanhs** [comment]
also, we can chat https://gitter.im/TranslucentTB/Lobby

**Comment by charlesmilette** [comment]
RAM usage in that case doesn't really matters, and making a GUI in C++ is more complicated

**Comment by olliethepikachu** [comment]
My point. Python allows for really easy GUI creation. If you want I can help with that. Just offering.

**Comment by ethanhs** [comment]
I was thinking that if it gets a GUI, it would be WPF C++. I don't know if it would make too much of a difference in resource difference, but I'd like to find out.

**Comment by olliethepikachu** [comment]
C# and C++ probably shouldn't have too much of an overhead. Python will result in large executables but still a decently small memory footprint, and a said Python app can be run when a GUI is needed and exited when it's done.

**Comment by ethanhs** [comment]
@olliethepikachu I have been programming with Python for 3 years now, it is by far my favorite programming language, but I just don't think its fit for this. In addition, you not only get the overhead of Python, but Qt when you ship PyQt, and it has to be GPL licensed (which I am still debating about).

Anyway, I think I will not have a GUI beyond the tray for now, but you two are encouraged to write your own (I'd be happy to link if you want). Let me know.

**Comment by olliethepikachu** [comment]
Yup. WPF would be pretty lightweight. PySide is free for commercial use (in fact my own projects involving GUIs are using it), and it is pretty much the same as PyQt syntactically. (No need for GPL licensing). I'll pass unless it really is needed, as I am pretty limited on time.

**Comment by charlesmilette** [comment]
We can run the GUI in C# also only when required.

Anyways, enough arguing about languages. Each one has its own advantages.

Le mar. 10 janv. 2017 20:40, olliethepikachu <notifications@github.com> a
écrit :

> Yup. WPF would be pretty lightweight. PySide is free for commercial use
> (in fact my own projects involving GUIs are using it), and it is pretty
> much the same as PyQt syntactically. (No need for GPL licensing). I'll pass
> unless it really is needed, as I am pretty limited on time.
>

**Comment by olliethepikachu** [comment]
Agreed that all languages have their advantages. @ethanhs has said he doesn’t want a GUI and tbh I’m too lazy to make one for essentially no reason. :D

**Comment by ethanhs** [comment]
@charlesmilette yeah, that works.

@olliethepikachu I know about PySide, I am a member of the Github organization if you look at my profile. Also, I meant _I_ don't want to write it now. If @charlesmilette wants to write a WPF one, I'd be happy to call it, perhaps it can be a button in the tray.

**Comment by olliethepikachu** [comment]
Fair enough. Still, if @charlesmilette were to make a GUI it would be fairly useless right now. Maybe until a few more options are implemented?

**Comment by charlesmilette** [comment]
Right now it would be totally useless, there's nothing to configure. Maybe
the GUI could implement auto-start right now, but that's pretty much it.

Le mar. 10 janv. 2017 20:54, olliethepikachu <notifications@github.com> a
écrit :

> Fair enough. Still, if @charlesmilette were to make a GUI it would be
> fairly useless right now. Maybe until a few more options are implemented?
>

**Comment by ethanhs** [comment]
Yes. That will come probably with V3

**Pull request closed without merging**
